import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import AuthProvider from "@/Provider/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hero Courses",
  description: "Generated by Adi",
};



export default function RootLayout({ children }) {

  return (
    <html lang="en" data-theme="light">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <div className="sticky top-0 z-10"><Navbar></Navbar></div>
            <div className="flex-1">
              {children}
            </div>
            <div><Footer></Footer></div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
